>P1;template
Structure:iapp:FIRST:A:LAST:L::-1.00:-1.00:
-KCNTATCATQRLANFLVHSSNNFGAILSSTNVGSNTY-/
-KCNTATCATQRLANFLVHSSNNFGAILSSTNVGSNTY-/
-KCNTATCATQRLANFLVHSSNNFGAILSSTNVGSNTY-/
-KCNTATCATQRLANFLVHSSNNFGAILSSTNVGSNTY-*

>P1;sequence
sequence:target::::::-1.00:-1.00:
-KCNTATCATQRLANFLVHSSNNFGAILSSTNVGSNTY-/
-KCNTATCATQRLANFLVHSSNNFGAILSSTNVGSNTY-/
DAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVV/
DAEFRHDSGYEVHHQKLVFFAEDVGSNKGAIIGLMVGGVV*

